#!/bin/bash
# Wrapper script around auto-cpufreq using the python virtual environment

set -eu

# bailout function
err_exit() {
  echo "$(basename "$0"): ${1:-wrong invocation. try --help for help.}" 1>&2
  exit 1
}

# load python virtual environment
opt_path=/opt/auto-cpufreq
venv_bin_dir=$opt_path/venv/bin
. "$venv_bin_dir/activate"

PYTHONPATH=$opt_path $venv_bin_dir/python $venv_bin_dir/auto-cpufreq "$@"
