#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke stop auto-cpufreq.service >/dev/null || true
            deb-systemd-helper disable auto-cpufreq.service >/dev/null || true
        fi
        ;;
    purge)
        if [ -d /run/systemd/system ]; then
            deb-systemd-helper purge auto-cpufreq.service >/dev/null || true
        fi
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac



exit 0