name: Nix Flake

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"
  pull_request:

jobs:
  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Nix ❄️"
        uses: nixbuild/nix-quick-install-action@v30

      - name: "Nix Cache ❄️"
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}

      - name: "Build Nix Flake ❄️"
        run: nix build

      
