name: Ruff

on:
  push:
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - "LICENSE"
      - "AGENTS.md"
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Ruff lint
        run: poetry run ruff check .

      - name: Run Ruff format check
        run: poetry run ruff format --check .
